version: '3'


services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env.dev
    volumes:
      - static_volume:/usr/src/app/backend/static
      - media_volume:/usr/src/app/backend/media
    expose:
      - 8000
    restart: unless-stopped
    depends_on:
      - db

  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db
    restart: unless-stopped

  frontend:
    build:
      context: ./reactsneacker
      dockerfile: Dockerfile
    expose:
      - 3000
    restart: unless-stopped
    command: serve -s build -l 3000
    depends_on:
      - backend

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - static_volume:/usr/src/app/backend/static
      - media_volume:/usr/src/app/backend/media
    depends_on:
      - backend
      - frontend
  
  

volumes:
  postgres_data:
  static_volume:
  media_volume:
