# Generated by Django 4.0.3 on 2022-03-26 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactsneacker', '0002_alter_product_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.ManyToManyField(to='reactsneacker.size', verbose_name='Размеры'),
        ),
    ]
