# Generated by Django 4.0.3 on 2022-03-29 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactsneacker', '0003_remove_product_size_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingstar',
            name='value',
            field=models.SmallIntegerField(default=0, unique=True, verbose_name='Значение'),
        ),
    ]
