export const GET_LIST_PRODUCTS = 'GET_LIST_PRODUCTS'
export const SET_LIST_PRODUCTS = 'SET_LIST_PRODUCTS'
export const SHOW_LOADER_LIST = 'SHOW_LOADER_LIST'
export const HIDE_LOADER_LIST = 'HIDE_LOADER_LIST'

export const GET_DETAIL_PRODUCTS = 'GET_DETAIL_PRODUCTS'
export const SET_DETAIL_PRODUCTS = 'SET_DETAIL_PRODUCTS'
export const SHOW_LOADER_DETAIL = 'SHOW_LOADER_DETAIL'
export const HIDE_LOADER_DETAIL = 'HIDE_LOADER_DETAIL'

export const ADD_PRODUCT_BASKET = 'ADD_PRODUCT_BASKET'
export const REMOVE_PRODUCT_BASKET = 'REMOVE_PRODUCT_BASKET'

export const ADD_PRODUCT_FAVOURITE = 'ADD_PRODUCT_FAVOURITE'
export const REMOVE_PRODUCT_FAVOURITE = 'REMOVE_PRODUCT_FAVOURITE'

export const LOGIN_USER = 'LOGIN_USER'
export const LOGOUT_USER = 'LOGOUT_USER'
export const SIGNUP_USER = 'SIGNUP_USER'

export const SET_AUTH_TOKEN = 'SET_AUTH_TOKEN'
export const UNSET_AUTH_TOKEN = 'UNSET_AUTH_TOKEN'

export const GET_USER = "GET_USER"
export const SET_USER = "SET_USER"

export const UPDATE_USER = "UPDATE_USER"

export const SHOW_ALERT = "SHOW_ALERT"
export const HIDE_ALERT = "HIDE_ALERT"

export const SHOW_LOADER = 'SHOW_LOADER'
export const HIDE_LOADER = 'HIDE_LOADER'

export const ACTIVATE_USER = 'ACTIVATE_USER'

export const RESET_PASSWORD = 'RESET_PASSWORD'
export const CONFIRM_PASSWORD = 'CONFIRM_PASSWORD'

export const LEAVE_REVIEW = 'LEAVE_REVIEW'
export const SET_REVIEW = 'SET_REVIEW'

export const GET_FILTER_FIELDS = "GET_FILTER_FIELDS"
export const SET_FILTER_FIELDS = "SET_FILTER_FIELDS"

export const GET_ORDERS = "GET_ORDERS"
export const SET_ORDERS = "SET_ORDERS"

export const MAKE_ORDER = "MAKE_ORDER"
export const SUCCESS_ORDER = "SUCCESS_ORDER"

export const FIRST_UPDATE = 'FIRST_UPDATE'